[build]
builder = "nixpacks"
buildCommand = """
  npm install -g pnpm && \
  cd packages/database && \
  sleep 5 && \
  pnpm db:migrate && \
  sleep 5 && \
  pnpm db:generate && \
  sleep 5 && \
  cd ../.. && \
  pnpm install && \
  pnpm db:generate && \
  pnpm build:shared && \
  pnpm build:server && \
  pnpm start:server
"""


[deploy]
startCommand = "pnpm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[variables]
NIXPACKS_NODE_VERSION = "18"
NIXPACKS_PKGS = "nodejs pnpm"
