[build]
builder = "nixpacks"

buildCommand = "cd apps/server && pnpm install && pnpm build"

[deploy]
startCommand = "cd apps/server && pnpm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[nixpacks]
node_version = "16"
