[build]
builder = "nixpacks"
<<<<<<< HEAD
buildCommand = "npm install -g pnpm && pnpm install && pnpm db:migrate && pnpm db:generate && pnpm build:shared & pnpm build:server && pnpm star:server  "
=======
buildCommand = "npm install -g pnpm && pnpm install && pnpm build"
>>>>>>> origin/main

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[variables]
NIXPACKS_NODE_VERSION = "18"
NIXPACKS_PKGS = "nodejs pnpm"
