[build]
builder = "nixpacks"
buildCommand = "
npm install -g pnpm &&
pnpm install && pnpm build"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[variables]
NIXPACKS_NODE_VERSION = "18"
NIXPACKS_PKGS = "nodejs pnpm"
