[build]
builder = "nixpacks"
buildCommand = """
npm install -g pnpm && \
pnpm install && \
pnpm db:generate && \
pnpm build:shared && \
pnpm build:server
"""


[deploy]
startCommand = """
pnpm db:migrate && \
pnpm start:server
"""
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[variables]
NIXPACKS_NODE_VERSION = "18"
NIXPACKS_PKGS = "nodejs pnpm"
