[build]
builder = "nixpacks"
buildCommand = """
pnpm install &&
pnpm --filter @influencer-management/shared build &&
pnpm --filter @influencer-management/server build
"""

[deploy]
startCommand = "cd apps/server && pnpm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[nixpacks]
node_version = "16"
