[build]
builder = "nixpacks"
buildCommand = "npm install -g pnpm && pnpm install && pnpm db:generate && pnpm build:shared && pnpm build:server && pnpm --filter @influencer-management/client build"


[deploy]
startCommand = "PORT=4000 pnpm start:server & PORT=8080 pnpm --filter @influencer-management/client preview --host 0.0.0.0"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[variables]
NIXPACKS_NODE_VERSION = "18"
NIXPACKS_PKGS = "nodejs pnpm"
RAILWAY_INTERNAL_URL = "http://localhost:$PORT"
